### ISSUE TITLE
CMake support

### ISSUE THREAD

**Issue by kvanberendonck** [jhasse/chipmunkpp#7]
It would be nice to have CMake support including FindChipmunkpp if possible

**Comment by jhasse** [comment]
I'm not sure what you mean. Can't CMake use external libraries? And shouldn't FindChipmunkpp be part of CMake rather than Chipmunk++?

**Comment by kvanberendonck** [comment]
No, it's convention to provide FindChipmunkpp that looks where it's expected that chipmunkpp is installed (some even clone the repo if necessary).

To integrate cmake with this project you then copy the FindChipmunkpp file into your own repo and load it as a cmake module or access it via a git submodule (FindChipmunkpp should also detect itself as a submodule and just work).

**Comment by jhasse** [comment]
I see. IMHO this is a design flaw of CMake, because I don't want to add some files to my repo when I'm not using CMake for Chipmunk++ myself. Because then there's someone else requesting to add a file for another build system and I end up with lots of files that aren't used by Chipmunk++, only by external projects.

So sorry, I'll close this for now. I think [the Wiki](https://github.com/jhasse/chipmunkpp/wiki) will be a better place for instructions (and file snippets) on how to use Chipmunk++ with CMake.

**Comment by jhasse** [comment]
Follow up: I would merge a PR with CMake files though. It's just that I don't have time to work on this myself ;)
